-- MySQL Script generated by MySQL Workbench
-- Sun Jul 31 21:16:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P5
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `P5` ;

-- -----------------------------------------------------
-- Schema P5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P5` DEFAULT CHARACTER SET utf8 ;
USE `P5` ;

-- -----------------------------------------------------
-- Table `P5`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`User` ;

CREATE TABLE IF NOT EXISTS `P5`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`Post` ;

CREATE TABLE IF NOT EXISTS `P5`.`Post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `chapo` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `P5`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `P5`.`Comment` ;

CREATE TABLE IF NOT EXISTS `P5`.`Comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `post_id` INT UNSIGNED NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `P5`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `P5`.`Post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
